GET http://localhost:8080/informationPages

###

GET http://localhost:8080/categories/638a26b7603daa5e9d01c4fd



###
POST http://localhost:8080/informationPages/saveInformationPage


Content-Type:  application/json
{"informationPage":{
    "numberOfPages":242,
    
    }
}

###
DELETE http://localhost:8080/informationPages/deleteInformationPage/638a15cd9c653fa974f6d2e2


###

PUT  http://localhost:8080/product/6388de783963f059fca6a440

Content-Type: application/json
{
    "numberOrder":12,
    "name":"shoes",
    "address":"tel-aviv 12",
    "deliveryTime":"12/2/20 12:53",
    "numberProduct":1,
    "price":233
}